export const QUERY_KEYS = {
    // Product Type
    GET_LIST_PRODUCT_TYPE: 'GET_LIST_PRODUCT_TYPE',
    GET_PRODUCT_TYPE_DETAIL: 'GET_PRODUCT_TYPE_DETAIL',

    // Category
    GET_LIST_CATEGORIES: 'GET_LIST_CATEGORIES',
    GET_CATEGORY_DETAIL: 'GET_CATEGORY_DETAIL',
  };
  